apiVersion: v1
kind: Service
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
    - name: rabbitmq-ui
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 80
    - name: rabbitmq-tcp
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 5672
