apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:latest
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_USERNAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "bitnami"
            - name: RABBITMQ_HOST
              value: "rabbitmq.messaging.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"