apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: producer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_USERNAME
              value: user
            - name: RABBITMQ_PASSWORD
              value: bitnami
            - name: RABBITMQ_HOST
              value: rabbitmq.messaging.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"