alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

server:
  global:
    scrape_interval: 15s

  service:
    type: ClusterIP
    port: 9090

  extraScrapeConfigs:
    - job_name: 'producer'
      metrics_path: /metrics
      static_configs:
        - targets:
            - producer.messaging.svc.cluster.local:8000

    - job_name: 'consumer'
      metrics_path: /metrics
      static_configs:
        - targets:
            - consumer.messaging.svc.cluster.local:8001

  ingress:
    enabled: false  # Istio will handle ingress, so native Ingress is disabled
