apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
data:
  config.yaml: |
    # telemetry config contents
