apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rabbitmq-virtualservice
  namespace: rabbitmq
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/main-gateway
  http:
    - match:
        - uri:
            prefix: /rabbit
      rewrite:
        uri: /
      route:
        - destination:
            host: rabbitmq.rabbitmq.svc.cluster.local
            port:
              number: 15672